resources:
  containers:
  - container: wpilib2020
    image: wpilib/roborio-cross-ubuntu:2020-18.04
  - container: raspbian
    image:  wpilib/raspbian-cross-ubuntu:10-18.04
  - container: bionic
    image: wpilib/aarch64-cross-ubuntu:bionic-18.04

variables:
- group: Artifactory-Package-Publish

stages:
- stage: Build
  jobs:
  - job: Windows_64_Bit_Release
    pool:
      vmImage: 'windows-2019'

    timeoutInMinutes: 0

    steps:
      - checkout: self  # self represents the repo where the initial Pipelines YAML file was found
        submodules: true
      - script: |
          dir "c:\\program files\\mingw64\\bin"
          where mingw32-make
          where awk
          where bash
          exit 1
      - powershell: |
          mkdir build
          $ProgressPreference = 'SilentlyContinue'
          wget "https://download.java.net/java/ga/jdk11/openjdk-11_windows-x64_bin.zip" -O "build\jdk.zip"
        displayName: 'Download JDK'
      - task: JavaToolInstaller@0
        inputs:
          jdkSourceOption: localDirectory
          jdkFile: 'build/jdk.zip'
          jdkDestinationDirectory: 'build/jdkinst'
          jdkArchitectureOption: x64
      - powershell: |
          $ProgressPreference = 'SilentlyContinue'
          wget "https://www.nasm.us/pub/nasm/releasebuilds/2.14.02/win64/nasm-2.14.02-win64.zip" -O "nasm.zip"
          Expand-Archive "nasm.zip"
      - bash: |
          pacman msys/make
      - script: |
          @call "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Enterprise\\VC\\Auxiliary\\Build\\vcvars64.bat"
          set PATH=%PATH%;%CD%\nasm\nasm-2.14.02
          set PATH=%PATH%;%ANT_HOME%\bin
          gradlew build -PjenkinsBuild -PskipDebug
        displayName: 'Gradle Build'
      - script: |
          type "ffmpeg-build\\ffbuild\\config.log"
          dir /s x264
          dir /s "build\\windows-x86_64\\x264"
        condition: failed()
      - task: PublishPipelineArtifact@0
        inputs:
          artifactName: 'Win64Release'
          targetPath: 'gradleDir/outputs'
